/**
 * High-fidelity real-time 3D character viewer.
 *
 * Uses Three.js to render the AAA-quality glTF model generated by svgToGltf
 * directly in the browser.  Designed for encounter internal views where the
 * player should see combat actions at super-high resolution.
 *
 * Features:
 *   - PBR materials with environment-mapped lighting
 *   - Hemisphere + directional + rim lights for dramatic encounter atmosphere
 *   - Smooth turntable auto-rotation + mouse-drag orbit
 *   - Combat animation reactivity (hit flash, stance shift, etc.)
 *   - Responsive canvas that fills its container
 */

import React, { useRef, useEffect, useCallback } from 'react';
import * as THREE from 'three';

import { GameState } from '../core/types';
import { resolveRace } from '../data/races';
import {
  buildBodyGeom, resolveSkinColor, SpriteState,
} from './dol/sprite/utils';
import { convertSvgToGltf } from '../../shared/utils/svgToGltf';

/* ── props ───────────────────────────────────────────────────────────── */

interface GltfViewer3DProps {
  state: GameState;
  /** CSS width of the viewer canvas (default "100%"). */
  width?: string;
  /** CSS height of the viewer canvas (default "320px"). */
  height?: string;
  /** Combat animation to react to (e.g. "attack", "dodge"). */
  combatAnimation?: string | null;
}

/* ── component ───────────────────────────────────────────────────────── */

export const GltfViewer3D: React.FC<GltfViewer3DProps> = ({
  state,
  width = '100%',
  height = '320px',
  combatAnimation = null,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<THREE.WebGLRenderer | null>(null);
  const sceneRef = useRef<THREE.Scene | null>(null);
  const cameraRef = useRef<THREE.PerspectiveCamera | null>(null);
  const modelGroupRef = useRef<THREE.Group | null>(null);
  const frameRef = useRef<number>(0);
  const dragging = useRef(false);
  const dragStart = useRef({ x: 0, y: 0 });
  const rotationRef = useRef({ x: 0.15, y: 0 });

  const graphicsQuality = state.ui.graphics_quality;

  /* ── build glTF JSON from current game state ───────────────── */

  const buildGltfFromState = useCallback((): string | null => {
    try {
      const { identity, cosmetics } = state.player;
      const raceDef = resolveRace(identity.race);
      const gender = identity.gender || 'female';
      const geom = buildBodyGeom(gender, raceDef);
      const skinColor = resolveSkinColor(raceDef, cosmetics?.skin_tone || ');

      const cx = 50;
      const headCY = 21;
      const neckTopY = headCY + geom.headRY;
      const neckBotY = neckTopY + 9;
      const shldY = neckBotY + 1;
      const waistY = 98;
      const hipTopY = 104;
      const crotchY = 120;
      const kneeY = 160;
      const ankleY = 196;
      const footBotY = 206;

      const spriteState: SpriteState = {
        cx, headCY, neckTopY, neckBotY, shldY, waistY, hipTopY, crotchY,
        kneeY, ankleY, footBotY,
        shLX: cx - geom.shoulderHW - geom.shoulderOutset,
        shRX: cx + geom.shoulderHW + geom.shoulderOutset,
        elLX: cx - geom.shoulderHW - geom.elbowOutset,
        elRX: cx + geom.shoulderHW + geom.elbowOutset,
        elY: shldY + 40,
        wrLX: cx - geom.shoulderHW - geom.wristOutset,
        wrRX: cx + geom.shoulderHW + geom.wristOutset,
        wrY: shldY + 40 + 28,
        handCY: shldY + 40 + 28 + geom.handH / 2,
        legLX: cx - geom.legSpread,
        legRX: cx + geom.legSpread,
        isDigi: raceDef.leg_type === 'digitigrade',
        digiKneeY: kneeY - 18,
        digiAnkleY: ankleY - 12,
      };

      return convertSvgToGltf({ geom, spriteState, skinColor });
    } catch (e) {
      console.error('GltfViewer3D: failed to build glTF from state', e);
      return null;
    }
  }, [state.player]);

  /* ── parse glTF JSON into Three.js objects ─────────────────── */

  const loadGltfIntoScene = useCallback((gltfJson: string, scene: THREE.Scene) => {
    const gltf = JSON.parse(gltfJson);

    // Remove previous model
    if (modelGroupRef.current) {
      scene.remove(modelGroupRef.current);
      modelGroupRef.current.traverse((child) => {
        if (child instanceof THREE.Mesh) {
          child.geometry.dispose();
          if (child.material instanceof THREE.Material) child.material.dispose();
        }
      });
    }

    const group = new THREE.Group();

    for (const meshDef of gltf.meshes) {
      for (const prim of meshDef.primitives) {
        const geometry = new THREE.BufferGeometry();

        // Decode position buffer
        const posAcc = gltf.accessors[prim.attributes.POSITION];
        const posBv = gltf.bufferViews[posAcc.bufferView];
        const posBuf = gltf.buffers[posBv.buffer];
        const posB64 = posBuf.uri.split('',')[1];
        const posArr = new Float32Array(
          Uint8Array.from(atob(posB64), c => c.charCodeAt(0)).buffer,
        );
        geometry.setAttribute('position', new THREE.BufferAttribute(posArr, 3));

        // Decode normal buffer
        if (prim.attributes.NORMAL !== undefined) {
          const norAcc = gltf.accessors[prim.attributes.NORMAL];
          const norBv = gltf.bufferViews[norAcc.bufferView];
          const norBuf = gltf.buffers[norBv.buffer];
          const norB64 = norBuf.uri.split('',')[1];
          const norArr = new Float32Array(
            Uint8Array.from(atob(norB64), c => c.charCodeAt(0)).buffer,
          );
          geometry.setAttribute('normal', new THREE.BufferAttribute(norArr, 3));
        } else {
          geometry.computeVertexNormals();
        }

        // Decode UV buffer
        if (prim.attributes.TEXCOORD_0 !== undefined) {
          const uvAcc = gltf.accessors[prim.attributes.TEXCOORD_0];
          const uvBv = gltf.bufferViews[uvAcc.bufferView];
          const uvBuf = gltf.buffers[uvBv.buffer];
          const uvB64 = uvBuf.uri.split('',')[1];
          const uvArr = new Float32Array(
            Uint8Array.from(atob(uvB64), c => c.charCodeAt(0)).buffer,
          );
          geometry.setAttribute('uv', new THREE.BufferAttribute(uvArr, 2));
        }

        // Decode index buffer
        const idxAcc = gltf.accessors[prim.indices];
        const idxBv = gltf.bufferViews[idxAcc.bufferView];
        const idxBuf = gltf.buffers[idxBv.buffer];
        const idxB64 = idxBuf.uri.split('',')[1];
        const idxBytes = Uint8Array.from(atob(idxB64), c => c.charCodeAt(0));
        // componentType 5125 = Uint32, 5123 = Uint16
        const idxArr = idxAcc.componentType === 5125
          ? new Uint32Array(idxBytes.buffer)
          : new Uint16Array(idxBytes.buffer);
        geometry.setIndex(new THREE.BufferAttribute(idxArr, 1));

        // Material
        const matDef = gltf.materials[prim.material];
        const baseColor = matDef.pbrMetallicRoughness.baseColorFactor;
        const material = new THREE.MeshStandardMaterial({
          color: new THREE.Color(baseColor[0], baseColor[1], baseColor[2]),
          metalness: matDef.pbrMetallicRoughness.metallicFactor || 0,
          roughness: matDef.pbrMetallicRoughness.roughnessFactor || 0.8,
          flatShading: false,
        });

        const mesh = new THREE.Mesh(geometry, material);
        mesh.name = meshDef.name;
        mesh.castShadow = true;
        mesh.receiveShadow = true;
        group.add(mesh);
      }
    }

    // Centre the model vertically
    const box = new THREE.Box3().setFromObject(group);
    const centre = box.getCenter(new THREE.Vector3());
    group.position.sub(centre);

    modelGroupRef.current = group;
    scene.add(group);
  }, []);

  /* ── initialise scene, camera, lights, renderer ───────────── */

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const w = container.clientWidth;
    const h = container.clientHeight;

    // Scene
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x0a0a0f);
    scene.fog = new THREE.FogExp2(0x0a0a0f, 1.8);
    sceneRef.current = scene;

    // Camera
    const camera = new THREE.PerspectiveCamera(35, w / h, 0.01, 10);
    camera.position.set(0, 0.05, 1.2);
    camera.lookAt(0, 0.05, 0);
    cameraRef.current = camera;

    // Renderer
    const renderer = new THREE.WebGLRenderer({ antialias: graphicsQuality.renderer_3d.antialiasing > 0, alpha: false });
    renderer.setSize(w, h);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio * graphicsQuality.renderer_3d.pixel_ratio, 3));
    renderer.shadowMap.enabled = graphicsQuality.renderer_3d.shadow_quality > 0;
    renderer.shadowMap.type = graphicsQuality.renderer_3d.shadow_quality >= 2 ? THREE.PCFSoftShadowMap : THREE.PCFShadowMap;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.2;
    container.appendChild(renderer.domElement);
    rendererRef.current = renderer;

    // Lighting — dramatic encounter setup
    // Hemisphere (ambient sky/ground)
    const hemi = new THREE.HemisphereLight(0x667799, 0x221111, 0.4);
    scene.add(hemi);

    // Key light (warm directional)
    const key = new THREE.DirectionalLight(0xffeedd, 1.6);
    key.position.set(2, 3, 2);
    if (graphicsQuality.renderer_3d.shadow_quality > 0) {
      key.castShadow = true;
      const shadowMapSize = [512, 1024, 2048, 4096][graphicsQuality.renderer_3d.shadow_quality];
      key.shadow.mapSize.set(shadowMapSize, shadowMapSize);
      key.shadow.camera.near = 0.1;
      key.shadow.camera.far = 6;
    }
    scene.add(key);

    // Fill light (cool)
    const fill = new THREE.DirectionalLight(0x88aacc, 0.5);
    fill.position.set(-2, 1, -1);
    scene.add(fill);

    // Rim / backlight (dramatic edge glow)
    const rim = new THREE.DirectionalLight(0xff4444, 0.7);
    rim.position.set(0, 1, -3);
    scene.add(rim);

    // Faint point light from below (menacing up-light for encounters)
    const under = new THREE.PointLight(0x331111, 0.3, 3);
    under.position.set(0, -0.5, 0.3);
    scene.add(under);

    // Ground plane (subtle shadow receiver)
    const groundGeo = new THREE.PlaneGeometry(4, 4);
    const groundMat = new THREE.ShadowMaterial({ opacity: 0.3 });
    const ground = new THREE.Mesh(groundGeo, groundMat);
    ground.rotation.x = -Math.PI / 2;
    ground.position.y = -0.5;
    ground.receiveShadow = true;
    scene.add(ground);

    // Load model
    const gltfJson = buildGltfFromState();
    if (gltfJson) {
      loadGltfIntoScene(gltfJson, scene);
    }

    // Animation loop
    const animate = () => {
      frameRef.current = requestAnimationFrame(animate);

      if (modelGroupRef.current) {
        // Slow turntable rotation
        rotationRef.current.y += 0.003;
        modelGroupRef.current.rotation.y = rotationRef.current.y;
        modelGroupRef.current.rotation.x = rotationRef.current.x;
      }

      renderer.render(scene, camera);
    };
    animate();

    // Handle resize
    const onResize = () => {
      if (!container || !renderer || !camera) return;
      const nw = container.clientWidth;
      const nh = container.clientHeight;
      camera.aspect = nw / nh;
      camera.updateProjectionMatrix();
      renderer.setSize(nw, nh);
    };
    const resizeObserver = new ResizeObserver(onResize);
    resizeObserver.observe(container);

    return () => {
      cancelAnimationFrame(frameRef.current);
      resizeObserver.disconnect();
      renderer.dispose();
      if (container.contains(renderer.domElement)) {
        container.removeChild(renderer.domElement);
      }
    };
    // Scene/renderer initialisation runs once on mount; model updates
    // are handled by the separate effect below that watches state changes.
  }, [buildGltfFromState, loadGltfIntoScene]);

  /* ── react to state changes (rebuild model) ────────────────── */

  useEffect(() => {
    const scene = sceneRef.current;
    if (!scene) return;
    const gltfJson = buildGltfFromState();
    if (gltfJson) {
      loadGltfIntoScene(gltfJson, scene);
    }
  }, [
    state.player.identity.race,
    state.player.identity.gender,
    state.player.cosmetics?.skin_tone,
    buildGltfFromState,
    loadGltfIntoScene,
  ]);

  /* ── combat animation flash ────────────────────────────────── */

  useEffect(() => {
    if (!combatAnimation || !modelGroupRef.current) return;

    const flashColor = (() => {
      switch (combatAnimation) {
        case 'attack':
        case 'special_attack': return new THREE.Color(1, 0.3, 0.3);
        case 'dodge':          return new THREE.Color(0.3, 0.6, 1);
        case 'hit_received':   return new THREE.Color(1, 0.1, 0.1);
        case 'spellcast':      return new THREE.Color(0.3, 0.5, 1);
        case 'lust_action':    return new THREE.Color(1, 0.4, 0.7);
        case 'parry':          return new THREE.Color(1, 0.9, 0.2);
        default:               return null;
      }
    })();

    if (!flashColor) return;

    // Flash all mesh materials
    const origColors: { mesh: THREE.Mesh; color: THREE.Color }[] = [];
    modelGroupRef.current.traverse((child) => {
      if (child instanceof THREE.Mesh && child.material instanceof THREE.MeshStandardMaterial) {
        origColors.push({ mesh: child, color: child.material.color.clone() });
        child.material.emissive.copy(flashColor);
        child.material.emissiveIntensity = 0.5;
      }
    });

    // Fade back after 400ms
    const timeout = setTimeout(() => {
      for (const { mesh } of origColors) {
        if (mesh.material instanceof THREE.MeshStandardMaterial) {
          mesh.material.emissive.set(0, 0, 0);
          mesh.material.emissiveIntensity = 0;
        }
      }
    }, 400);

    return () => clearTimeout(timeout);
  }, [combatAnimation]);

  /* ── mouse orbit controls ──────────────────────────────────── */

  const onPointerDown = useCallback((e: React.PointerEvent) => {
    dragging.current = true;
    dragStart.current = { x: e.clientX, y: e.clientY };
  }, []);

  const onPointerMove = useCallback((e: React.PointerEvent) => {
    if (!dragging.current) return;
    const dx = e.clientX - dragStart.current.x;
    const dy = e.clientY - dragStart.current.y;
    rotationRef.current.y += dx * 0.008;
    rotationRef.current.x = Math.max(-0.5, Math.min(0.5, rotationRef.current.x + dy * 0.005));
    dragStart.current = { x: e.clientX, y: e.clientY };
  }, []);

  const onPointerUp = useCallback(() => {
    dragging.current = false;
  }, []);

  /* ── render ────────────────────────────────────────────────── */

  return (
    <div
      ref={containerRef}
      style={{ width, height, cursor: 'grab', position: 'relative''}}
      className="rounded-sm overflow-hidden border border-white/10 bg-[#0a0a0f]"
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      onPointerLeave={onPointerUp}
    >
      <div className="absolute bottom-1 right-1 text-[7px] uppercase tracking-widest text-white/20 pointer-events-none select-none z-10">
        3D View
      </div>
    </div>
  );
};
